apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: steamgame
  labels:
    app: steamgame
spec:
  replicas: 1
  selector:
      matchLabels:
        app: steamgame
  template:
    metadata:
      labels:
        app: steamgame
    spec:
      containers:
      - name: steamgame
        image: mrsigurniv/steamgame:latest
        command:
        ports:
          - containerPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: steamgame
spec:
  selector:
    app: steamgame
  type: NodePort
  ports:
  - port: 8081
    protocol: TCP
    nodePort: 31002
    name: steamgame