apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: steamprice
  labels:
    app: steamprice
spec:
  replicas: 1
  selector:
      matchLabels:
        app: steamprice
  template:
    metadata:
      labels:
        app: steamprice
    spec:
      containers:
      - name: steamprice
        image: mrsigurniv/steamprice:latest
        command:
        ports:
          - containerPort: 8083
---
kind: Service
apiVersion: v1
metadata:
  name: steamprice
spec:
  selector:
    app: steamprice
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
    nodePort: 31003
    name: steamprice